apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dns-scheduler
spec:
  template:
    spec:
      serviceAccountName: "dns-scheduler-app@default.iam.gserviceaccount.com" # from-param: ${service_account_email}
      containers:
        - image: dns-scheduler
          env:
            - name: NEXTDNS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: NEXTDNS_API_KEY
                  key: latest
            - name: NEXTDNS_PROFILE_ID_0
              valueFrom:
                secretKeyRef:
                  name: NEXTDNS_PROFILE_ID_0
                  key: latest
            - name: NEXTDNS_PROFILE_ID_1
              valueFrom:
                secretKeyRef:
                  name: NEXTDNS_PROFILE_ID_1
                  key: latest
            - name: DOMAIN_DENY_LIST
              value: "" # from-param: ${domain_deny_list}
            - name: DOMAIN_ALLOW_LIST
              value: "" # from-param: ${domain_allow_list}
