steps:
  - name: "gcr.io/cloud-builders/docker"
    id: build
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/dns-scheduler-repo/dns-scheduler:${SHORT_SHA}"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: push
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/dns-scheduler-repo/dns-scheduler:${SHORT_SHA}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: create-release
    entrypoint: "gcloud"
    args:
      - "deploy"
      - "releases"
      - "create"
      - "release-${SHORT_SHA}"
      - "--delivery-pipeline=dns-scheduler-pipeline"
      - "--region=${_REGION}"
      - "--to-target=prod"
      - "--images=dns-scheduler=${_REGION}-docker.pkg.dev/${PROJECT_ID}/dns-scheduler-repo/dns-scheduler:${SHORT_SHA}"
      - "--deploy-parameters=service_account_email=dns-scheduler-app@${PROJECT_ID}.iam.gserviceaccount.com"
    waitFor:
      - push

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/dns-scheduler-repo/dns-scheduler:${SHORT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY
