services:
  otel:
    container_name: otel
    image: us-docker.pkg.dev/cloud-ops-agents-artifacts/google-cloud-opentelemetry-collector/otelcol-google:0.143.0
    command: ["--config=/etc/otelcol-google/config.yaml"]
    volumes:
      - ./otel-config-dev.yaml:/etc/otelcol-google/config.yaml:ro
    environment:
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID}
